live_config_reload = true

[colors]
primary = { foreground = "#ffffff", background = "#000000" }

[window]
opacity = 0.95
title = "gabrielms"
decorations = "Buttonless"

[font]
size = 18
normal = { "family" = "GeistMono NF", "style" = "SemiBold" }
