# Ported from ghostty config

# Colors
background            #000000
foreground            #ffffff
background_opacity    0.95

# Font
font_family           GeistMono NF SemiBold
font_size             18
macos_thicken_font    0.75
# ghostty: font-feature = -calt / -dlig / -liga
disable_ligatures     always

# Cursor
cursor_shape          block
shell_integration     no-cursor

# Window
confirm_os_window_close   0
hide_window_decorations   yes
macos_window_shadow       no
mouse_hide_wait           3.0
