#!/usr/bin/env sh

source "$HOME/.config/colors.sh"

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# yabai -m config \
# 	mouse_follows_focus off \
# 	focus_follows_mouse off \
# 	window_origin_display default \
# 	window_placement second_child \
# 	window_zoom_persist off \
# 	window_shadow on \
# 	window_animation_duration 0.0 \
# 	window_animation_frame_rate 120 \
# 	window_opacity_duration 0.0 \
# 	active_window_opacity 1.0 \
# 	normal_window_opacity 1.0 \
# 	window_opacity off \
# 	insert_feedback_color 0xffd75f5f \
# 	split_ratio 0.50 \
# 	split_type auto \
# 	auto_balance off \
# 	top_padding 31 \
# 	bottom_padding 10 \
# 	left_padding 10 \
# 	right_padding 10 \
# 	window_gap 10 \
# 	layout bsp \
# 	mouse_modifier fn \
# 	mouse_action1 move \
# 	mouse_action2 resize \
# 	mouse_drop_action swap \
#
#
# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on 
yabai -m config window_border_width          4

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  35
yabai -m config bottom_padding               10
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   10

yabai -m rule --add app="^(Finder|System Settings|System Information|Activity Monitor|FaceTime|Screen Sharing|Calculator|Stickies|TinkerTool|Progressive Downloader|Transmission|Airflow)$" manage=off
yabai -m rule --add app="^Arc$" title="^$" mouse_follows_focus=off
yabai -m signal --add event=window_focused action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".split == \"horizontal\"" && yabai -m window --toggle split'

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"

echo "yabai configuration loaded.."
