local Remap = require("gabrielmartins.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<leader>fp", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<C-p>", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<leader>ff", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<leader>fl", function()
    require('telescope.builtin').diagnostics()
end)
nnoremap("<leader>fk", function()
    require('telescope.builtin').lsp_references({bufnr = 0})
end)
nnoremap("<leader>fi", function()
    require('telescope.builtin').lsp_incoming_calls()
end)
--[[
nnoremap("<leader>fw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
nnoremap("<leader>fm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
--]]
nnoremap("<leader>fh", function()
    require('telescope.builtin').help_tags()
end)
nnoremap("<leader>fb", function()
    require('gabrielmartins.telescope').git_branches()
end)
